### ISSUE TITLE
orientdb 2.2.2  connection error 

### ISSUE THREAD

**Issue by arslantopcu** [mogui/pyorient#200] opened 2016-06-20 06:26 UTC
ValueError: invalid literal for int() with base 10: '0 (build develop@r79d281140b01c0bc3b566a46a64f1573cb359783; 2016'

pyorient = 1.5.2
orientdb = 2.2.2
python   = 2.7

**Comment by TommyBrown** [comment] 2016-06-22 21:07
I am getting this error as well.

pyorient = 1.5.2
orientdb = 2.2.0
python = 2.7

**Comment by princelySid** [comment] 2016-06-23 09:54
Getting a similar error:
`ValueError: invalid literal for int() with base 10: '0 (build UNKNOWN@r; 2015'`
pyorient: 1.5.2
orientdb: 2.1.0
python: 2.7

**Comment by Ostico** [comment] 2016-06-29 12:38
Hi all,
that issued should be fixed in pyorient v1.5.4. Try to update. 
If the issue is still present, please send me some other infos and re-open the issue.

I need to know exactly what version of OrientDB you are using. 
The version number is not enough because OrientDB present himself with different version strings, i'd like to know where you got it ( downloaded or from which repository you built it ).

**Closed by Ostico** 2016-06-29 12:38 UTC
